// eslint-disable-next-line no-unused-vars
const data = [
  {
    fname: "𝕄𝕖𝕛𝕚𝕕",
    lname: "Netcrawler",
    lastword: "The Money Is The Motive !💸💰",
    longText:
      "Son Of A Gun We made it through. And This is my token of rememberance for ya all.I hope we find peace in our separate ways and be still in full to get reunited someday.",
    photo: "mejid-min.jpg",
    sampleImages: [
      "mejid1.jpg",
      "mejid2.jpg",
      "mejid-min.jpg",
      "mejid4.jpg",
      "mejid5.jpg",
      "mejid6.jpg",
    ],
  },
  {
    fname: "Dave",
    lname: "Woy yoy",
    lastword: "አትለኝም!! ... ሁላችንም አስመሳዮች ነን !",
    longText: "",
    photo: "dave-min.jpg",
    sampleImages: [
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
    ],
  },
  {
    fname: "Henok",
    lname: "Henooks",
    lastword: "last word goes here",
    longText: "",
    photo: "enoch-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Eyoas",
    lname: "Eyosi",
    lastword:
      "From effortless learning to unforgettable smiles, I’ve lived my dreams like Em's track",
    longText: "",
    photo: "eyoas-min.jpg",
    sampleImages: [
      "eyoas1.jpg",
      "eyoas2.jpg",
      "eyoas3.jpg",
      "eyoas4.jpg",
      "eyoas-min.jpg",
      "eyoas6.jpg",
    ],
  },
  {
    fname: "Abel",
    lname: "Paps",
    lastword: "last word goes here ",
    longText: "",
    photo: "abel-min.jpg",
    sampleImages: [
      "papa1.jpg",
      "papa2.jpg",
      "papa3.jpg",
      "papa4.jpg",
      "papa5.jpg",
      "papa6.jpg",
    ],
  },
  {
    fname: "Barnabas",
    lname: "Barni",
    lastword: "Don't be afraid",
    longText:
      "Nothing lasts forever, but at least we've got these memories. In a world where everything changes, our memories are the precious moments we keep. They remind us of the good times, the lessons we've learned, and the people we've loved.",
    photo: "barni-min.jpg",
    sampleImages: [
      "barni1.jpg",
      "barni2.jpg",
      "barni3.jpg",
      "barni4.jpg",
      "barni5.jpg",
      "barni6.jpg",
    ],
  },
  {
    fname: "Tomas",
    lname: "Tomi Boi",
    lastword: "metahulsh merkato sefere",
    longText:
      "ከ ሃዋሳ ተነስቼ beayertena adrge ... be torayloch shortcut  ..beabent aderge yhew metahulsh merkato sefere",
    photo: "tomi-min.jpg",
    sampleImages: [
      "tomi1.jpg",
      "tomi2.jpg",
      "tomi3.jpg",
      "tomi4.jpg",
      "tomi5.jpg",
      "tomi6.jpg",
    ],
  },
  {
    fname: "Kenehirian",
    lname: "Kenji",
    lastword: "God Did !",
    longText: "",
    photo: "kenji-min.jpg",
    sampleImages: [
      "kenji1.jpg",
      "kenji2.jpg",
      "kenji3.jpg",
      "kenji4.jpg",
      "kenji5.jpg",
      "kenji6.jpg",
    ],
  },
  {
    fname: "Nuredin",
    lname: "Nura",
    lastword: "Leave Your Legacy !",
    longText:
      "Life’s purpose?the purpose of life is to worship and serve Allah, live righteously, and strive for eternal salvation in the hereafter. Muslims believe that this life is a test and preparation for the afterlife.",
    photo: "nura-min.jpg",
    sampleImages: [
      "nura1.jpg",
      "nura2.jpg",
      "nura3.jpg",
      "nura4.jpg",
      "nura5.jpg",
      "nura6.jpg",
    ],
  },
  {
    fname: "Eyob Dula",
    lname: "Eyoba",
    lastword: "የረዳኝን እግዚአብሔርን አመሰግናለሁ  መዝ 12፥6",
    longText:
      "The past three years were a period in which I had not accomplished certain goals, and they were not my most successful. However, it was during this time that I learned the most valuable lessons for my life.",
    photo: "eyob-min.jpg",
    sampleImages: [
      "eyob1.jpg",
      "eyob2.jpg",
      "eyob3.jpg",
      "eyob4.jpg",
      "eyob5.jpg",
      "eyob-min.jpg",
    ],
  },
  {
    fname: "Amanuel Gadissa",
    lname: "Macroni",
    lastword: "Trust The Process ! 🔫",
    longText:
      "Breaking news:No class for today🤸‍♀,mejid' macroni,Ye lab kulf manga new?'Kefe yet neh? 'Library, ke moti ategeb' Beki 'rice rice baby' ,Kid 'the teacher is waiting us ,please be fast,🏃🏃 demo ye binder birr laku!' Abeni'Cap. Yet neh?,benja kulf askemtual?'Nefsi aroge libs kale....... I miss you!",
    photo: "aman2.jpg",
    sampleImages: [
      "aman1.JPG",
      "aman2.jpg",
      "aman3.jpg",
      "aman4.JPG",
      "aman5.jpg",
      "aman6.JPG",
    ],
  },
  {
    fname: "Abduljelil",
    lname: "AJ",
    lastword:
      "Allah does not burden a soul beyond that it can bear” [Al-Baqarah 2:286]",
    longText:
      "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ",
    photo: "aj6.jpg",
    sampleImages: [
      "aj1.jpg",
      "aj2.jpg",
      "aj3.jpg",
      "aj4.jpg",
      "aj5.jpg",
      "aj6.jpg",
    ],
  },
  {
    fname: "Dagmawi",
    lname: "Dagi Daddy ah!",
    lastword: "Son Of A Bald !! or Should i say ... የመላጣ ልጅ ",
    longText: "",
    photo: "dagi-min.jpg",
    sampleImages: [
      "dagi1.jpg",
      "dagi2.jpg",
      "dagi3.jpg",
      "dagi4.jpg",
      "dagi5.jpg",
      "dagi6.jpg",
    ],
  },
  {
    fname: "Bereket",
    lname: "Beki",
    lastword: "በህይወቴ ደስተኛ ነኝ",
    longText: "",
    photo: "beki-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Biruk",
    lname: "Biruuuuk",
    lastword: "Through God's Grace Alone, Without My Efforts",
    longText:
      "Stay curious, work hard, and embrace challenges. Your dedication will shape your future. Support each other, stay positive, and always strive for excellence. በጣም ትናፍቁኛላችሁ :: ሁላችሁንም እጅግ በጣም ወዳችኃለው🥰",
    photo: "bura5.jpg",
    sampleImages: [
      "bura1.jpg",
      "bura2.jpg",
      "bura3.jpg",
      "bura4.jpg",
      "bura5.jpg",
      "bura6.jpg",
    ],
  },
  {
    fname: "Zeynedin",
    lname: "Zizu",
    lastword: "ለዐለማቱ ጌታ አላህ ምሰጋና ሁሉ የተገባው ነው!",
    longText:
      "Hey guys,I just wanted to say a huge thanks to all of you who were part of my university journey. You all made it an amazing experience, and I miss you a ton! Thanks for all the laughs, late-night study sessions, and everything in between. Hope to see you soon and catch up.With tears...Take care and keep rocking!Love CS🥰",
    photo: "zeynu-min.jpg",
    sampleImages: [
      "zeynu1.jpg",
      "zeynu2.jpg",
      "zeynu3.jpg",
      "zeynu4.jpg",
      "zeynu5.jpg",
      "zeynu6.jpg",
    ],
  },
  {
    fname: "Ziyad",
    lname: "Zizu",
    lastword: "Surviving Is Winning Everything Else Is Bullshit",
    longText: "",
    photo: "ziyad2.jpg",
    sampleImages: [
      "ziyad1.png",
      "ziyad2.jpg",
      "ziyad3.png",
      "ziyad4.jpg",
      "ziyad5.jpg",
      "ziyad6.jpg",
    ],
  },
];

export default data;
