// eslint-disable-next-line no-unused-vars
const data = [
  {
    fname: "Mejid",
    lname: "Netcrawler",
    lastword: "",
    photo: "mejid-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Dave",
    lname: "Woy yoy",
    lastword: "አትለኝም!! ... ሁላችንም አስመሳዮች ነን !",
    longText: "",
    photo: "dave-min.jpg",
    sampleImages: [
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
    ],
  },
  {
    fname: "Henok",
    lname: "Henooks",
    lastword: "selam selam Enoch ebalalew",
    longText: "",
    photo: "enoch-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Eyoas",
    lname: "Eyosi",
    lastword: "Haily I know u mish ur mash ",
    longText: "",
    photo: "eyoas-min.jpg",
    sampleImages: [
      "eyoas1.jpg",
      "eyoas2.jpg",
      "eyoas3.jpg",
      "eyoas4.jpg",
      "eyoas5.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Abel",
    lname: "Paps",
    lastword: "Tenu is My Mother ",
    longText: "",
    photo: "abel-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Barnabas",
    lname: "Barni",
    lastword: "Niggas 🥷 Be Counting ME up",
    longText: "",
    photo: "barni-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Thomas",
    lname: "Tomi Boi",
    lastword: "Im Sexy and i Know it",
    longText: "",
    photo: "tomi-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Kenhirian",
    lname: "Kenji",
    lastword: "Everyday MILFs be testing me Ah !",
    longText: "",
    photo: "kenji-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Nuredin",
    lname: "Nura",
    lastword: "Leave Your Legacy !",
    longText: "",
    photo: "nura-min.jpg",
    sampleImages: [
      "nura1.jpg",
      "nura2.jpg",
      "nura3.jpg",
      "nura4.jpg",
      "nura5.jpg",
      "nura6.jpg",
    ],
  },
  {
    fname: "Eyob Dula",
    lname: "Eyoba",
    lastword: "የረዳኝን እግዚአብሔርን አመሰግናለሁ  መዝ 12፥6",
    longText:
      "The past three years were a period in which I had not accomplished certain goals, and they were not my most successful. However, it was during this time that I learned the most valuable lessons for my life.",
    photo: "eyob-min.jpg",
    sampleImages: [
      "eyob1.jpg",
      "eyob2.jpg",
      "eyob3.jpg",
      "eyob4.jpg",
      "eyob5.jpg",
      "eyob-min.jpg",
    ],
  },
  {
    fname: "Amanuel Gadissa",
    lname: "Macroni",
    lastword: "....",
    longText: "....",
    photo: "aman2.jpg",
    sampleImages: [
      "aman1.JPG",
      "aman2.jpg",
      "aman3.jpg",
      "aman4.jpg",
      "aman5.jpg",
      "aman6.JPG",
    ],
  },
  {
    fname: "Abduljelil",
    lname: "AJ",
    lastword: "ፈጀኋቸው!! ምኖቹን እንዳትሉኝ you know me  ",
    longText: "",
    photo: "aj1.jpg",
    sampleImages: [
      "aj2.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Dagmawi",
    lname: "Dagi Daddy ah!",
    lastword: "Son Of A Bald !! or Should i say ... የመላጣ ልጅ ",
    longText: "",
    photo: "dagi-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Bereket",
    lname: "Beki",
    lastword: "በህይወቴ ደስተኛ ነኝ",
    longText: "",
    photo: "beki-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Biruk",
    lname: "Dejene",
    lastword: "Through God's Grace Alone, Without My Efforts",
    longText:
      "Stay curious, work hard, and embrace challenges. Your dedication will shape your future. Support each other, stay positive, and always strive for excellence. በጣም ትናፍቁኛላችሁ :: ሁላችሁንም እጅግ በጣም ወዳችኃለው🥰",
    photo: "bura5.jpg",
    sampleImages: [
      "bura1.jpg",
      "bura2.jpg",
      "bura3.jpg",
      "bura4.jpg",
      "bura5.jpg",
      "bura6.jpg",
    ],
  },
];

export default data;
