// eslint-disable-next-line no-unused-vars
const data = [
  {
    id: 1,
    fname: "Mejid",
    lname: "Netcrawler",
    lastword: "The Money Is The Motive",
    photo: "mejid-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    fname: "Dave",
    lname: "Woy yoy",
    lastword: "አትለኝም!! ... ሁላችንም አስመሳዮች ነን !",
    photo: "dave-min.jpg",
    sampleImages: [
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
      "dave-min.jpg",
    ],
  },
  {
    id: 2,
    fname: "Henok",
    lname: "Henooks",
    lastword: "selam selam Enoch ebalalew",
    photo: "enoch-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    id: 3,
    fname: "Eyoas",
    lname: "Eyosi",
    lastword: "Haily I know u mish ur mash ",
    photo: "eyoas-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    id: 4,
    fname: "Abel",
    lname: "Paps",
    lastword: "Tenu is My Mother ",
    photo: "abel-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    id: 5,
    fname: "Barnabas",
    lname: "Barni",
    lastword: "Niggas 🥷 Be Counting ME up",
    photo: "barni-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    id: 5,
    fname: "Thomas",
    lname: "Tomi Boi",
    lastword: "Im Sexy and i Know it",
    photo: "tomi-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    id: 6,
    fname: "Kenhirian",
    lname: "Kenji",
    lastword: "Everyday MILFs be testing me Ah !",
    photo: "kenji-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    id: 8,
    fname: "Nuredin",
    lname: "Nura",
    lastword: "I do Snaps For A living!",
    photo: "nura-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    id: 9,
    fname: "Abduljelil",
    lname: "AJ",
    lastword: "ፈጀኋቸው!! ምኖቹን እንዳትሉኝ you know me  ",
    photo: "abdu-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    id: 10,
    fname: "Dagmawi",
    lname: "Dagi Daddy ah!",
    lastword: "Son Of A Bald !! or Should i say ... የመላጣ ልጅ ",
    photo: "dagi-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
  {
    id: 11,
    fname: "Bereket",
    lname: "Beki",
    lastword: "በህይወቴ ደስተኛ ነኝ",
    photo: "beki-min.jpg",
    sampleImages: [
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
      "mejid-min.jpg",
    ],
  },
];

export default data;
